<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PromotionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $promotions = [
            // 1. Diskon Persentase
            [
                'name' => 'Diskon Akhir Tahun',
                'code' => 'TAHUNBARU2025',
                'description' => 'Diskon spesial untuk menyambut tahun baru',
                'type' => 'percentage',
                'discount_value' => 25.00,
                'max_discount' => 100000.00,
                'min_purchase' => 200000.00,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::now()->subDays(5),
                'end_date' => Carbon::now()->addDays(25),
                'usage_limit' => 100,
                'usage_per_customer' => 1,
                'current_usage' => 12,
                'target_type' => 'all',
                'target_ids' => null,
                'is_active' => true,
                'priority' => 10,
                'is_stackable' => false,
                'badge_text' => 'HEMAT 25%',
                'badge_color' => '#FF5722',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /**
            // 2. Diskon Nominal/Fixed
            [
                'name' => 'Potongan Belanja Pertama',
                'code' => 'WELCOME50K',
                'description' => 'Potongan Rp 50.000 untuk pelanggan baru',
                'type' => 'fixed',
                'discount_value' => 50000.00,
                'max_discount' => null,
                'min_purchase' => 150000.00,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::now()->subDays(10),
                'end_date' => Carbon::now()->addMonths(1),
                'usage_limit' => null,
                'usage_per_customer' => 1,
                'current_usage' => 45,
                'target_type' => 'all',
                'target_ids' => null,
                'is_active' => true,
                'priority' => 8,
                'is_stackable' => false,
                'badge_text' => 'HEMAT 50RB',
                'badge_color' => '#4CAF50',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ], */

            // 3. Buy X Get Y
            [
                'name' => 'Beli 2 Gratis 1',
                'code' => 'BUY2GET1',
                'description' => 'Beli 2 produk pilihan gratis 1 produk termurah',
                'type' => 'buy_x_get_y',
                'discount_value' => null,
                'max_discount' => null,
                'min_purchase' => null,
                'buy_quantity' => 2,
                'get_quantity' => 1,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::now()->subDays(3),
                'end_date' => Carbon::now()->addDays(15),
                'usage_limit' => 200,
                'usage_per_customer' => 3,
                'current_usage' => 67,
                'target_type' => 'specific_products',
                'target_ids' => json_encode([1, 2, 3, 5, 8]),
                'is_active' => true,
                'priority' => 9,
                'is_stackable' => false,
                'badge_text' => 'BELI 2 GRATIS 1',
                'badge_color' => '#E91E63',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /**
            // 4. Bundle
            [
                'name' => 'Paket Hemat 3 Item',
                'code' => 'BUNDLE3',
                'description' => 'Beli 3 item hanya Rp 99.000',
                'type' => 'bundle',
                'discount_value' => null,
                'max_discount' => null,
                'min_purchase' => null,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => 99000.00,
                'bundle_quantity' => 3,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addDays(30),
                'usage_limit' => 150,
                'usage_per_customer' => 5,
                'current_usage' => 23,
                'target_type' => 'category',
                'target_ids' => json_encode([1, 2]),
                'is_active' => true,
                'priority' => 7,
                'is_stackable' => false,
                'badge_text' => 'PAKET HEMAT',
                'badge_color' => '#9C27B0',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 5. Cashback
            [
                'name' => 'Cashback 15%',
                'code' => 'CASHBACK15',
                'description' => 'Dapatkan cashback 15% hingga Rp 50.000',
                'type' => 'cashback',
                'discount_value' => null,
                'max_discount' => null,
                'min_purchase' => 100000.00,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => 15.00,
                'max_cashback' => 50000.00,
                'start_date' => Carbon::now()->subDays(7),
                'end_date' => Carbon::now()->addDays(20),
                'usage_limit' => 300,
                'usage_per_customer' => 2,
                'current_usage' => 89,
                'target_type' => 'all',
                'target_ids' => null,
                'is_active' => true,
                'priority' => 6,
                'is_stackable' => true,
                'badge_text' => 'CASHBACK 15%',
                'badge_color' => '#00BCD4',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 6. Free Shipping
            [
                'name' => 'Gratis Ongkir',
                'code' => 'FREESHIPNOV',
                'description' => 'Gratis ongkir untuk pembelian minimal Rp 50.000',
                'type' => 'free_shipping',
                'discount_value' => null,
                'max_discount' => null,
                'min_purchase' => 50000.00,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::now()->startOfMonth(),
                'end_date' => Carbon::now()->endOfMonth(),
                'usage_limit' => null,
                'usage_per_customer' => 10,
                'current_usage' => 234,
                'target_type' => 'all',
                'target_ids' => null,
                'is_active' => true,
                'priority' => 5,
                'is_stackable' => true,
                'badge_text' => 'GRATIS ONGKIR',
                'badge_color' => '#FF9800',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 7. Seasonal - Ramadhan
            [
                'name' => 'Promo Ramadhan',
                'code' => 'RAMADHAN2025',
                'description' => 'Diskon spesial menyambut bulan suci Ramadhan',
                'type' => 'seasonal',
                'discount_value' => 20.00,
                'max_discount' => 75000.00,
                'min_purchase' => 250000.00,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::create(2025, 3, 1),
                'end_date' => Carbon::create(2025, 4, 30),
                'usage_limit' => 500,
                'usage_per_customer' => 5,
                'current_usage' => 0,
                'target_type' => 'all',
                'target_ids' => null,
                'is_active' => false, // Belum aktif
                'priority' => 10,
                'is_stackable' => false,
                'badge_text' => 'PROMO RAMADHAN',
                'badge_color' => '#673AB7',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 8. Flash Sale
            [
                'name' => 'Flash Sale Midnight',
                'code' => 'FLASHMIDNIGHT',
                'description' => 'Diskon 40% hanya berlaku tengah malam',
                'type' => 'percentage',
                'discount_value' => 40.00,
                'max_discount' => 200000.00,
                'min_purchase' => 100000.00,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::now()->subHours(2),
                'end_date' => Carbon::now()->addHours(2),
                'usage_limit' => 50,
                'usage_per_customer' => 1,
                'current_usage' => 38,
                'target_type' => 'specific_products',
                'target_ids' => json_encode([2, 4, 6, 7]),
                'is_active' => true,
                'priority' => 15, // Highest priority
                'is_stackable' => false,
                'badge_text' => 'FLASH SALE 40%',
                'badge_color' => '#F44336',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 9. Member Exclusive
            [
                'name' => 'Member Premium',
                'code' => 'PREMIUM10',
                'description' => 'Diskon eksklusif untuk member premium',
                'type' => 'percentage',
                'discount_value' => 10.00,
                'max_discount' => null,
                'min_purchase' => null,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::now()->subMonths(1),
                'end_date' => null, // Permanent
                'usage_limit' => null,
                'usage_per_customer' => null, // Unlimited
                'current_usage' => 456,
                'target_type' => 'all',
                'target_ids' => null,
                'is_active' => true,
                'priority' => 3,
                'is_stackable' => true,
                'badge_text' => 'MEMBER 10%',
                'badge_color' => '#FFD700',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 10. Promo yang sudah expired
            [
                'name' => 'Promo Halloween',
                'code' => 'HALLOWEEN2024',
                'description' => 'Promo spesial Halloween (sudah berakhir)',
                'type' => 'percentage',
                'discount_value' => 31.00,
                'max_discount' => 150000.00,
                'min_purchase' => 200000.00,
                'buy_quantity' => null,
                'get_quantity' => null,
                'bundle_price' => null,
                'bundle_quantity' => null,
                'cashback_percentage' => null,
                'max_cashback' => null,
                'start_date' => Carbon::create(2024, 10, 25),
                'end_date' => Carbon::create(2024, 10, 31),
                'usage_limit' => 100,
                'usage_per_customer' => 1,
                'current_usage' => 87,
                'target_type' => 'all',
                'target_ids' => null,
                'is_active' => false,
                'priority' => 10,
                'is_stackable' => false,
                'badge_text' => 'HALLOWEEN 31%',
                'badge_color' => '#FF5722',
                'image' => null,
                'created_at' => Carbon::create(2024, 10, 20),
                'updated_at' => Carbon::create(2024, 11, 1),
            ], */
        ];

        DB::table('promotions')->insert($promotions);

        $this->command->info('✅ Promotions seeded successfully!');
        $this->command->info('📊 Total promotions created: ' . count($promotions));
    }
}